rm/urls.py
from django.conf.urls import url
from django.shortcuts import render

from . import views

app_name = 'rm'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),

    url(r'^trashes/$', views.trash_list_view, name='trashes'),
    url(r'^trashes/(?P<pk>[0-9]+)/$', views.trash_detail_view, name='trash_detail'),
    url(r'^trashes/create/$', views.trash_create_view, name='trash_create'),
    url(r'^trashes/delete/$', views.trash_delete, name='trash_delete'),
    url(r'^trashes/clear/$', views.trash_clear, name='trash_clear'),
    
    url(r'^operations/$', views.operation_list_view, name='operations'),
    url(r'^operations/(?P<pk>[0-9]+)/$', views.operation_detail_view, name='operation_detail'),
    url(r'^operations/create/$', views.operation_create_view, name='operation_create'),
    url(r'^operations/delete/(?P<pk>[0-9]+)/$', views.operation_delete_view, name='operation_delete'),
    url(r'^operations/restore/(?P<pk>[0-9]+)/$', views.operation_restore_view, name='operation_restore'),
]

rmsite2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('rm.urls')),
]

rm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os.path
import shutil

from datetime import timedelta
from datetime import datetime

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.http import Http404

from .managers import TrashManager, OperationManager

from smartrm2.trash import Trash as Smartrm2Trash
from smartrm2.config import Config
from smartrm2.rmerror import RMError
from smartrm2.rm import get_new_operation_id
from smartrm2.helpers.operation_helper import get_operation_files, delete_operation, restore_operation


class Trash(models.Model):
    path = models.CharField(max_length=255, unique=True)

    restore_policy = models.CharField(
        max_length=30, 
        choices=(
            ('passive', 'passive'),
            ('aggressive', 'aggressive'),
        ),
        default='passive',
    )

    maxtime = models.DurationField(default=timedelta(seconds=0))
    maxsize = models.BigIntegerField(default=0)
    maxnumber = models.BigIntegerField(default=0)

    create_time = models.DateTimeField(default=datetime.now)

    objects = TrashManager()

    def delete(self, *args, **kwargs):
        if os.path.exists(self.path):
            shutil.rmtree(self.path)

        super(Trash, self).delete(*args, **kwargs)

    def clear(self):
        self.get_smartrm2_trash().clear()

    def get_smartrm2_trash(self):
        config = Config(
            trashpath=self.path,
            restore_policy=self.restore_policy,
            autoclear_policies={'maxtime': self.maxtime.total_seconds()},
            maxsize=self.maxsize,
            maxnumber=self.maxnumber,
        )

        if not config.autoclear_policies['maxtime']:
            config.autoclear_policies = None

        return Smartrm2Trash(config)

    def __unicode__(self):
        return os.path.basename(self.path.rstrip('/'))


class Operation(models.Model):
    id = models.CharField(max_length=31, primary_key=True, unique=True,
                          default=get_new_operation_id())
    name = models.CharField(max_length=100, blank=True)
    trash = models.ForeignKey(Trash, on_delete=models.CASCADE)
    create_time = models.DateTimeField(default=datetime.now)

    objects = OperationManager()

    def restore_files(self, path, policy):
        smartrm2_trash = self.trash.get_smartrm2_trash()
        smartrm2_trash.config.restore_policy = policy
        
        try:
            restore_operation(int(self.id), smartrm2_trash, path)
        except RMError:
            pass

    def delete_files(self, path):
        smartrm2_trash = self.trash.get_smartrm2_trash()

        try:
            delete_operation(int(self.id), smartrm2_trash, path)
        except RMError:
            pass

    def delete(self, *args, **kwargs):
        smartrm2_trash = self.trash.get_smartrm2_trash()

        try:
            delete_operation(int(self.id), smartrm2_trash, '')
        except RMError:
            pass
            
        super(Operation, self).delete(*args, **kwargs)

    def get_files(self):
        return get_operation_files(
                   int(self.id), 
                   self.trash.get_smartrm2_trash()
               )

    def __unicode__(self):
        return self.name if self.name else self.id

rm/forms.py
from django import forms

from .models import Trash
from .validators import trash_path_validator, operation_paths_validator, operation_name_validator, abspaths_validator


class TrashForm(forms.Form):
	path = forms.CharField(max_length=100, validators=[trash_path_validator,])
	
	restore_policy = forms.ChoiceField(choices=(
		('passive', 'passive'),
		('aggressive', 'aggressive'),
	))
	
	maxtime_hours = forms.IntegerField(min_value=0, max_value=999, initial=0)
	maxtime_minutes = forms.IntegerField(min_value=0, max_value=59, initial=0)
	maxtime_seconds = forms.IntegerField(min_value=0, max_value=59, initial=0)
	maxsize = forms.IntegerField(min_value=0, max_value=10**12, initial=0)
	maxnumber = forms.IntegerField(min_value=0, max_value=10**6, initial=0)


class OperationForm(forms.Form):
	name = forms.CharField(max_length=30, required=False, 
		                   validators=[operation_name_validator,])

	paths = forms.CharField(widget=forms.Textarea, max_length=300,
		                    validators=[operation_paths_validator,])
	
	trash = forms.ModelChoiceField(queryset=Trash.objects.all())
	
	regex = forms.CharField(max_length=30, required=False)

	dry_run = forms.BooleanField(required=False)


class OperationRestoreForm(forms.Form):
	policy = forms.ChoiceField(choices=(
		('passive', 'passive'),
		('aggressive', 'aggressive'),
	))

	paths = forms.CharField(widget=forms.Textarea, max_length=300,
							validators=[abspaths_validator,])


class OperationDeleteForm(forms.Form):
	paths = forms.CharField(widget=forms.Textarea, max_length=300,
							validators=[abspaths_validator])

rm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views.decorators.http import require_http_methods

from datetime import timedelta

from .models import Trash, Operation
from .forms import TrashForm, OperationForm, OperationRestoreForm, OperationDeleteForm

from smartrm2.rmerror import RMError


def index_view(request):
    return render(request, 'rm/index.html', {})


def trash_list_view(request):
    return render(
               request, 
               'rm/trashes.html', 
               {'trashes': Trash.objects.all()}
           )


def trash_detail_view(request, pk):
    trash = get_object_or_404(Trash, pk=pk)
    return render(request, 'rm/trash_detail.html', {'trash': trash})


def trash_create_view(request):
    if request.method == 'POST':
        form = TrashForm(request.POST)
        if form.is_valid():
            try:
                trash = Trash.objects.create_trash(
                    path=form.cleaned_data['path'], 
                    restore_policy=form.cleaned_data['restore_policy'],
                    maxtime=timedelta(
                        seconds=form.cleaned_data['maxtime_hours']*60*60 +\
                                form.cleaned_data['maxtime_minutes']*60 +\
                                form.cleaned_data['maxtime_seconds']
                    ),
                    maxsize=form.cleaned_data['maxsize'],
                    maxnumber=form.cleaned_data['maxnumber'],
                )
            except RMError as exc:
                return render(
                           request, 
                           'rm/error.html', 
                           {'message': exc.message}
                       )

            return HttpResponseRedirect(reverse('rm:trashes'))

    form = TrashForm()
    return render(request, 'rm/trash_create.html', {'form': form})


@require_http_methods(["POST",])
def trash_delete(request):
    trash = Trash.objects.get(pk=request.POST['pk'])
    trash.delete()
    return HttpResponseRedirect(reverse('rm:trashes'))


@require_http_methods(["POST",])
def trash_clear(request):
    trash = Trash.objects.get(pk=request.POST['pk'])
    trash.clear()
    return HttpResponseRedirect(reverse('rm:trashes'))


def operation_list_view(request):
    return render(
               request, 
               'rm/operations.html', 
               {'operations': Operation.objects.all()}
           )


def operation_detail_view(request, pk):
    operation = get_object_or_404(Operation, pk=pk)
    return render(
               request, 
               'rm/operation_detail.html', 
               {'operation': operation}
           )


def operation_create_view(request):
    if request.method == 'POST':
        form = OperationForm(request.POST)
        if form.is_valid():
            try:
                if form.cleaned_data['dry_run']:
                    files = Operation.objects.create_operation(
                        paths=form.cleaned_data['paths'],
                        name=form.cleaned_data['name'],
                        trash=form.cleaned_data['trash'],
                        regex=form.cleaned_data['regex'],
                        dry_run=form.cleaned_data['dry_run']
                    )

                    return render(
                               request, 
                               'rm/operation_create_dry_run.html', 
                               {'files': files}
                           )

                Operation.objects.create_operation(
                    paths=form.cleaned_data['paths'],
                    name=form.cleaned_data['name'],
                    trash=form.cleaned_data['trash'],
                    regex=form.cleaned_data['regex'],
                    dry_run=form.cleaned_data['dry_run']
                )
                return HttpResponseRedirect(reverse('rm:operations')) 
            except RMError as exc:
                return render(
                           request, 
                           'rm/error.html', 
                           {'message': exc.message}
                       )

    form = OperationForm()
    return render(request, 'rm/operation_create.html', {'form': form})


def operation_delete_view(request, pk):
    if request.method == 'POST':
        form = OperationDeleteForm(request.POST)
        if form.is_valid():
            operation = get_object_or_404(Operation, pk=pk)
            paths = [ path.strip() 
                      for path in form.cleaned_data['paths'].split(';')]

            for path in paths:
                if path:
                    operation.delete_files(path)
            return HttpResponseRedirect(reverse('rm:operations'))

    operation = get_object_or_404(Operation, pk=pk)
    form = OperationDeleteForm()
    return render(
               request, 
               'rm/operation_delete.html', 
               {'form': form, 'operation': operation}
           )


def operation_restore_view(request, pk):
    if request.method == 'POST':
        form = OperationRestoreForm(request.POST)
        if form.is_valid():
            operation = get_object_or_404(Operation, pk=pk)
            paths = [ path.strip() 
                      for path in form.cleaned_data['paths'].split(';')]

            for path in paths:
                if path:
                    operation.restore_files(
                        path, 
                        form.cleaned_data['policy']
                    )
            return HttpResponseRedirect(reverse('rm:operations'))

    operation = get_object_or_404(Operation, pk=pk)
    form = OperationRestoreForm()
    return render(
               request, 
               'rm/operation_restore.html', 
               {'form': form, 'operation': operation}
           )

rm/templates/rm/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %}{% endblock %}</title>

		<link href="{% static 'rm/css/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'rm/css/font-awesome.css' %}" rel="stylesheet">
		<link type="text/css" href="{% static 'rm/css/style.css' %}" rel="stylesheet">
	</head>
  
	<body background="FF69B4">
		<div class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="{% url 'rm:trashes' %}">
						<i class="fa fa-trash"></i>
						Trashes
					</a>
					<a class="navbar-brand" href="{% url 'rm:operations' %}">
						<i class="fa fa-edit"></i>
						Operations
					</a>
				</div>
			</div>
		</div>
		<div style="background-color: rgba(0, 255, 255, .3);">
			<hr>
			<h1 align="center">{% block header%}{% endblock%}</h1>
			<hr>
		</div>
		{% block content %}{% endblock %}

	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	    <script src="{% static 'rm/js/bootstrap.js' %}"></script>
	</body>
</html>

rm/templates/rm/error.html
{% extends "rm/base.html" %}

{% block title %}Error{% endblock %}

{% block header%}Error{% endblock %}

{% block content %}
	<div class="container">
		{{ message }}
	</div>
{% endblock %}

rm/templates/rm/index.html
{% extends "rm/base.html" %}

{% block title %}RMSite 2{% endblock %}

{% block header%}RMSite 2{% endblock %}

{% block content %}

{% endblock %}

rm/templates/rm/operation_create.html
{% extends "rm/base.html" %}

{% block title %}Create operation{% endblock %}

{% block header%}Create operation{% endblock %}

{% block content %}
	<div class="container">
		<form role="form" action="{% url 'rm:operation_create' %}" method="post">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">
					<i class="fa fa-check"></i>
					Create
				</button>
			</div>
		</form>

		<form action="{% url 'rm:trashes' %}">
			<button class="btn btn-default" type="submit">
				<i class="fa fa-undo"></i>
				Back
			</button>
		</form>
	</div>
{% endblock %}

rm/templates/rm/operation_create_dry_run.html
{% extends "rm/base.html" %}

{% block title %}Dry-run{% endblock %}

{% block header%}Dry-run{% endblock %}

{% block content %}
	<div class="container">
		<table class="table table-hover table-condensed" align="center">
			<tr>
				<th>Files</th>
			</tr>
			{% for file in files %}
				<tr>
					<td>{{ file }}</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

rm/templates/rm/operation_delete.html
{% extends "rm/base.html" %}

{% block title %}Delete operation{% endblock %}

{% block header%}Delete {{operation}}{% endblock %}

{% block content %}
	<div class="container">
		<form role="form" action="{% url 'rm:operation_delete' operation.pk %}" method="post">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-danger" type="submit">
					<i class="fa fa-check"></i>
					Delete
				</button>
			</div>
		</form>
	</div>
{% endblock %}

rm/templates/rm/operation_detail.html
{% extends "rm/base.html" %}

{% block title %}Operation {{ operation }}{% endblock %}

{% block header%}{{ operation }}{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operation_restore' operation.pk %}">
						<button class="btn btn-success" type="submit">
							<i class="fa fa-share-square-o"></i>
							Restore
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operation_delete' operation.pk %}">
						<button class="btn btn-danger" type="submit">
							<i class="fa fa-remove"></i>
							Delete
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operations' %}">
						<button class="btn btn-default" type="submit">
							<i class="fa fa-arrow-left"></i>
							Back
						</button>
					</form>
				</div>
			</div>
		</div>
		<table class="table table-hover table-condensed" align="center">
			<tr>
				<th>Files</th>
				<th>Size</th>
			</tr>
			{% for file in operation.get_files %}
				<tr>
					<td>{{ file.oldpath }}</td>
					<td>{{ file.size|filesizeformat }}</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

rm/templates/rm/operation_restore.html
{% extends "rm/base.html" %}

{% block title %}Restore operation{% endblock %}

{% block header%}Restore {{operation}}{% endblock %}

{% block content %}
	<div class="container">
		<form role="form" action="{% url 'rm:operation_restore' operation.pk %}" method="post">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">
					<i class="fa fa-check"></i>
					Restore
				</button>
			</div>
		</form>
	</div>
{% endblock %}

rm/templates/rm/operations.html
{% extends "rm/base.html" %}

{% block title %}Operations{% endblock %}

{% block header%}Operations{% endblock %}

{% block content %}
	<div class="container">
		<div class="form-group" align="left">
			<form action="{% url 'rm:operation_create' %}" method="get">
				<button class="btn btn-success" type="submit">
					<i class="fa fa-plus-circle"></i>
					New operation
				</button>
			</form>
		</div>
		<table class="table table-hover table-condensed" align="center">
			<tr>
				<th>Name</th>
				<th>Trash</th>
				<th>Files</th>
				<th>Create time</th>
			</tr>
			{% for operation in operations %}
				<tr>
					<td><a href="{% url 'rm:operation_detail' operation.pk %}">{{ operation }}</a></td>
					<td><a href="{% url 'rm:trash_detail' operation.trash.pk %}">{{ operation.trash }}</a></td>
					<td>{{ operation.get_files|length }}</td>
					<td>{{ operation.create_time }}</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

rm/templates/rm/trash_create.html
{% extends "rm/base.html" %}

{% block title %}Create trash{% endblock %}

{% block header%}Create new trash{% endblock %}

{% block content %}
	<div class="container">
		<form role="form" action="{% url 'rm:trash_create' %}" method="post">
			<div class="form-group">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">
					<i class="fa fa-check"></i>
					Create
				</button>
			</div>
		</form>
		<form action="{% url 'rm:trashes' %}">
			<button class="btn btn-default" type="submit">
				<i class="fa fa-arrow-left"></i>
				Back
			</button>
		</form>
	</div>
{% endblock %}

rm/templates/rm/trash_detail.html
{% extends "rm/base.html" %}

{% block title %}Trash {{ trash }}{% endblock %}

{% block header%}{{ trash.path }}{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:trash_delete' %}" method="post">
						{% csrf_token %}
						<button name="pk" value="{{ trash.pk }}" class="btn btn-danger" type="submit">
							<i class="fa fa-remove"></i>
							Delete
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:trash_clear' %}" method="post">
						{% csrf_token %}
						<button name="pk" value="{{ trash.pk }}" class="btn btn-default" type="submit">
							<i class="fa fa-folder-o"></i>
							Clear
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:trashes' %}">
						<button class="btn btn-default" type="submit">
							<i class="fa fa-arrow-left"></i>
							Back
						</button>
					</form>
				</div>
			</div>
		</div>
		<div class="tabs">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#tab-1" data-toggle="tab">Operations</a></li>
				<li><a href="#tab-2" data-toggle="tab">Files</a></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane fade in active" id="tab-1">
					<table class="table table-hover table-condensed" align="center">
						<tr>
							<th>Name</th>
							<th>Files</th>
							<th>Create time</th>
						</tr>
						{% for operation in trash.operation_set.all %}
							<tr>
								<td><a href="{% url 'rm:operation_detail' operation.pk %}">{{ operation }}</a></td>
								<td>{{ operation.get_files|length }}</td>
								<td>{{ operation.create_time }}</td>
							</tr>
						{% endfor %}
					</table>
				</div> 
				<div class="tab-pane fade" id="tab-2">
					<table class="table table-hover table-condensed" align="center">
						<tr>
							<th>File</th>
							<th>Size</th>
						</tr>
						{% for file in trash.get_smartrm2_trash.get_trashfiles %}
							<tr>
								<td>{{ file.oldpath }}</td>
								<td>{{ file.size|filesizeformat }}</td>
							</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

rm/templates/rm/trashes.html
{% extends "rm/base.html" %}

{% block title %}Trashes{% endblock %}

{% block header%}Trashes{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:trash_create' %}">
						<button class="btn btn-success" type="submit">
							<i class="fa fa-plus-circle"></i>
							New trash
						</button>
					</form>
				</div>
			</div>
			<div class="col-md-1">
				<div class="form-group" align="left">
					<form action="{% url 'rm:operation_create' %}">
						<button class="btn btn-success" type="submit">
							<i class="fa fa-plus-circle"></i>
							New operation
						</button>
					</form>
				</div>
			</div>
		</div>
		<table class="table table-hover table-condensed" align="center">
			<tr>
				<th>Name</th>
				<th>Path</th>
				<th>Operations</th>
				<th>Files</th>
				<th>Size</th>
				<th>Maxtime</th>
				<th>Create time</th>
			</tr>
			{% for trash in trashes %}
				<tr>
					<td><a href="{% url 'rm:trash_detail' trash.pk %}">{{ trash }}</a></td>
					<td>{{ trash.path }}</td>
					<td>{{ trash.operation_set.all|length }}</td>
					<td>
						{{ trash.get_smartrm2_trash.get_trashfiles|length }}
						{% if trash.maxnumber %}
							/ {{ trash.maxnumber }}
						{% endif %}
					</td>
					<td>
						{{ trash.get_smartrm2_trash.get_size_of_trash|filesizeformat }}
						{% if trash.maxsize %}
							/ {{ trash.maxsize|filesizeformat }}
						{% endif %}
					</td>
					<td>
						{% if trash.maxtime %}
							{{ trash.maxtime }}
						{% else %}
							-
						{% endif %}
					</td>
					<td>{{ trash.create_time }}</td>
					<!--
					<td>
						<form action="{% url 'rm:trash_clear' %}" method="post">
							{% csrf_token %}
							<button class="btn btn-link" name="pk" value={{ trash.pk }} type="submit">
								<i class="fa fa-check"></i>
							</button>
						</form>
					</td>
					<td>
						<form action="{% url 'rm:trash_delete' %}" method="post">
							{% csrf_token %}
							<button class="btn btn-link" name="pk" value={{ trash.pk }} type="submit">
								<i class="fa fa-check"></i>
							</button>
						</form>
					</td>
					-->
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}